"""バイトコードと ``__pycache__`` を実行で確認するサンプル。

実行内容:

1. 実行中の Python 実装とバージョンを表示する（CPython 3.12.x のはず）
2. 同じディレクトリの ``greeted`` モジュールを import する
   - 初回 import 時に CPython がバイトコードへ変換し、
     ``__pycache__/greeted.cpython-312.pyc`` を生成する
3. 生成された ``.pyc`` のパスとサイズを表示する
4. ``py_compile`` を使った明示的な事前コンパイルを実演する

詳しい背景は同ディレクトリの README.md を参照。
"""

from __future__ import annotations

import py_compile
import sys
from pathlib import Path

# `python samples/13_bytecode_and_pycache/main.py` のように直接実行された場合、
# このファイル自身のディレクトリが sys.path に含まれるので `greeted` を import できる。
import greeted  # noqa: E402  (説明上、import の位置をここに置く)


HERE = Path(__file__).resolve().parent


def show_implementation() -> None:
    impl = sys.implementation
    print(f"implementation : {impl.name}")            # 通常は 'cpython'
    print(f"version_info   : {sys.version_info}")     # (3, 12, 13, 'final', 0) など
    print(f"cache_tag      : {impl.cache_tag}")       # 'cpython-312' など


def show_pyc_for(module_name: str) -> None:
    """import 済みモジュールに対応する .pyc を探して表示する。"""
    cache_dir = HERE / "__pycache__"
    if not cache_dir.is_dir():
        print(f"(no __pycache__ yet for {module_name})")
        return
    matches = sorted(cache_dir.glob(f"{module_name}.*.pyc"))
    for pyc in matches:
        size = pyc.stat().st_size
        print(f"cached bytecode: {pyc.relative_to(HERE)}  ({size} bytes)")


def precompile_self() -> None:
    """py_compile による事前コンパイルの例。"""
    target = HERE / "greeted.py"
    pyc_path = py_compile.compile(str(target))
    print(f"py_compile out : {Path(pyc_path).relative_to(HERE)}")


def main() -> None:
    print("# 1. interpreter")
    show_implementation()

    print("\n# 2. greeted module was imported above")
    print(greeted.greet("alice"))

    print("\n# 3. .pyc generated by import")
    show_pyc_for("greeted")

    print("\n# 4. explicit ahead-of-time compile")
    precompile_self()


if __name__ == "__main__":
    main()
